### PR TITLE
fix: remove deprecated setAndForwardRef

### PR DESCRIPTION
**Pull request by yigitcan-prospr**
#### Issue
Can't resolve 'react-native/Libraries/Utilities/setAndForwardRef'

#### Summary

This library used `setAndForwardRef` from react-native internal functions which starting from RN v0.72 is no longer included (https://github.com/facebook/react-native/commit/bf6ed07c0f01f788e6554ad63c958feec3d2eb0c). This PR removes the imports from `react-native/Libraries/Utilities` and uses the `setAndForwardRef.ts` from previous RN versions (https://github.com/facebook/react-native/blob/7cf4cf3afbea4463427944fbed30768a796db724/Libraries/Utilities/setAndForwardRef.js).

### CODE REVIEW

**Comment by enahum** [comment]
Hi @yigitcan-prospr thanks for the PR.

can I ask you to please also update the RN version of the example app so we can quickly check that the changes are working as intended?

I think for the time being we can keep this PR until we move the lib to the new architecture ;)

**Comment by yigitcan-prospr** [comment]
> Hi @yigitcan-prospr thanks for the PR.
> 
> can I ask you to please also update the RN version of the example app so we can quickly check that the changes are working as intended?
> 
Sure thing.

> I think for the time being we can keep this PR until we move the lib to the new architecture ;)
>
That's great news! Though currently it's impossible to build after upgrading to 0.72 so I'm assuming many people will create issues about this. I think it might be reasonable to have an intermediate version before the big release with the new architecture support.

**Comment by enahum** [comment]
The android example app is not building, probably you missed some upgrade changes to build.gradle and settings.settings files

**Review by enahum — APPROVED** [review]

**Pull request merged**
